name = "gbr_js"
version = "1.0.5-alpha"
target = "javascript"

description = "Javascript library to gleam by @gleam-br."
repository = { type = "github", user = "gleam-br", repo = "gbr_js" }
licences = ["Apache-2.0"]
links = []

[dependencies]
gleam_stdlib = "~> 0.69"
gleam_javascript = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.9"

[javascript]
typescript_declarations = true
