name = "gbr_js"
version = "1.0.1-alpha+001"
target = "javascript"

description = "ðŸŽƒ Gleam javascript library by @gleam-br"
repository = { type = "github", user = "gleam-br", repo = "gbr_js" }
licences = ["Apache-2.0"]
# links = [{ title = "Website", href = "" }]

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.65"
gleam_javascript = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
